# -*- coding: utf-8 -*-
"""factorial using iterative and recursive

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hf1TrqXJ76iWzYjvLz8JixsVxEnwtaFb
"""

import time

def factorial_iterative(n):
    fact = 1

    for i in range(1, n + 1):
        fact = fact * i

    return fact

def factorial_recursive(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial_recursive(n - 1)

n = int(input("Enter a number: "))


start_time = time.perf_counter()
result_iterative = factorial_iterative(n)
end_time = time.perf_counter()

iterative_time = end_time - start_time


start_time = time.perf_counter()
result_recursive = factorial_recursive(n)
end_time = time.perf_counter()

recursive_time = end_time - start_time


print("\n--- Factorial Results ---")
print("Factorial using Iterative Method :", result_iterative)
print("Execution Time                  :", iterative_time, "seconds")

print("\nFactorial using Recursive Method :", result_recursive)
print("Execution Time                  :", recursive_time, "seconds")

print("\n--- Time Complexity ---")
print("Iterative Method : O(n)")
print("Recursive Method : O(n)")