# -*- coding: utf-8 -*-
"""graph and searching(bfs & dfs)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgDqe8kFrgEzKWkkwQpgsb3fgTBfOpAP
"""

from collections import deque

graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

def dfs(graph, start, visited=None):

    if visited is None:
        visited = set()

    visited.add(start)
    print(start, end=" ")

    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited)


def bfs(graph, start):

    visited = set()
    queue = deque([start])

    visited.add(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=" ")

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

print("DFS Traversal:")
dfs(graph, 'A')

print("\n\nBFS Traversal:")
bfs(graph, 'A')