# -*- coding: utf-8 -*-
"""Kruskal's Algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRdCPvB7ewbi_n4tID-Cfh-dioSrKGcK
"""

def find(parent, vertex):

    if parent[vertex] != vertex:
        parent[vertex] = find(parent, parent[vertex])

    return parent[vertex]

def union(parent, rank, x, y):

    root_x = find(parent, x)
    root_y = find(parent, y)

    if root_x != root_y:

        if rank[root_x] < rank[root_y]:
            parent[root_x] = root_y

        elif rank[root_x] > rank[root_y]:
            parent[root_y] = root_x

        else:
            parent[root_y] = root_x
            rank[root_x] += 1

edges = [
    (2, 0, 1),
    (3, 1, 2),
    (5, 1, 4),
    (6, 0, 3),
    (7, 2, 4),
    (8, 1, 3),
    (9, 3, 4)
]

V = 5

edges.sort()

parent = list(range(V))
rank = [0] * V

mst = []
total_cost = 0

print("Edges in Minimum Spanning Tree:")
print("Edge\tWeight")

for weight, u, v in edges:

    root_u = find(parent, u)
    root_v = find(parent, v)

    if root_u != root_v:

        mst.append((u, v, weight))
        total_cost += weight

        union(parent, rank, root_u, root_v)

        print(f"{u} - {v}\t{weight}")

    if len(mst) == V - 1:
        break

print("\nTotal cost of MST:", total_cost)