# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BAkIRhNEX-nhdfJGAVSGD-lnKU2USGfY
"""

import time

def bubble_sort(arr):
    n = len(arr)

    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

numbers = list(map(int, input("Enter numbers: ").split()))

start = time.perf_counter()
bubble_sort(numbers)
end = time.perf_counter()

print("Sorted List:", numbers)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best   : O(n)")
print("Average: O(n²)")
print("Worst  : O(n²)")

import time

def selection_sort(arr):
    n = len(arr)

    for i in range(n):
        min_index = i

        for j in range(i+1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        arr[i], arr[min_index] = arr[min_index], arr[i]

numbers = list(map(int, input("Enter numbers: ").split()))

start = time.perf_counter()
selection_sort(numbers)
end = time.perf_counter()

print("Sorted List:", numbers)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best   : O(n²)")
print("Average: O(n²)")
print("Worst  : O(n²)")

import time

def insertion_sort(arr):

    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1

        while j >= 0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1

        arr[j+1] = key

numbers = list(map(int, input("Enter numbers: ").split()))

start = time.perf_counter()
insertion_sort(numbers)
end = time.perf_counter()

print("Sorted List:", numbers)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best   : O(n)")
print("Average: O(n²)")
print("Worst  : O(n²)")

import time

def merge_sort(arr):
    if len(arr) > 1:

        mid = len(arr) // 2
        left = arr[:mid]
        right = arr[mid:]

        merge_sort(left)
        merge_sort(right)

        i = j = k = 0

        while i < len(left) and j < len(right):

            if left[i] < right[j]:
                arr[k] = left[i]
                i += 1
            else:
                arr[k] = right[j]
                j += 1

            k += 1

        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1

numbers = list(map(int, input("Enter numbers: ").split()))

start = time.perf_counter()
merge_sort(numbers)
end = time.perf_counter()

print("Sorted List:", numbers)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best   : O(n log n)")
print("Average: O(n log n)")
print("Worst  : O(n log n)")

import time

def quick_sort(arr):

    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr)//2]

    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return left + middle + right

numbers = list(map(int, input("Enter numbers: ").split()))

start = time.perf_counter()
sorted_list = quick_sort(numbers)
end = time.perf_counter()

print("Sorted List:", sorted_list)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity")
print("Best   : O(n log n)")
print("Average: O(n log n)")
print("Worst  : O(n²)")